### ISSUE TITLE
Nie ładujące się img.

### ISSUE THREAD

**Issue by iEmix** [iEmix/modernlib#1]
Nie chcą ładować się obrazy img z static.
Nie znajduję pliku nie wiem czemu mimo że style css znajduję a są w tym samym folderze.

**Comment by JasonSpine** [comment]
Już robiłem to jakiś czas temu, ale może ten kawałek mojego pliku **settings.py** coś Ci pomoże:
```
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

ENV_PATH = os.path.abspath(os.path.dirname(__file__))
if DEBUG:
	STATICFILES_DIRS = [
		os.path.join(BASE_DIR, "public/static"),
		'/var/www/static/',
	]

	STATIC_ROOT = os.path.join(BASE_DIR, "")
	MEDIA_ROOT = os.path.join(BASE_DIR, "public/media")
else:
	STATIC_ROOT = os.path.join(ENV_PATH, '../public/static/')
	MEDIA_ROOT = os.path.join(ENV_PATH, '../public/media/')
```

**Comment by iEmix** [comment]
Zmienił się błąd wcześniej plik nie istniał a teraz A server error occurred.  Please contact the administrator. no nic próbuje dalej i dzięki za pomoc

**Comment by iEmix** [comment]
```python
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
] 
```

**Comment by iEmix** [comment]
rozwiązany problem , dzięki za wskazanie kierunku
