### ISSUE TITLE
Liczba mnoga w bazie danych django

### ISSUE THREAD

**Issue by iEmix** [iEmix/modernlib#2]
W bazie danych po zalogowaniu wszystko jest w liczbie mnogiej dodaje s. Gdzie w języku polskim to się nie sprawdza.  Jak to zmienić
Autorzy - Autorzys
Ksiazki - Ksiazkis

**Comment by dchoruzy** [comment]
https://docs.djangoproject.com/en/1.9/ref/models/options/#verbose-name

**Comment by iEmix** [comment]
![image](https://user-images.githubusercontent.com/45265693/55982870-1ba49280-5c9a-11e9-994c-66ce269974d4.png) 
U mnie tak to wygląda a próbowałem metody z tamtego linku

**Comment by nowakowsky** [comment]
Musisz dodać do każdego modelu coś takiego: 

```
class Meta:
        verbose_name = "Użytkownik"
        verbose_name_plural = "Użytkownicy"
```

Tamten link jest do starej dokumentacji, tutaj masz nowy https://docs.djangoproject.com/en/2.2/

**Comment by iEmix** [comment]
dziękuje, problem rozwiązany.;)
